### Get all characters
GET http://localhost:3000/api/characters

### Update HP
PUT http://localhost:3000/api/characters/CH001/hp
Content-Type: application/json

{
  "hp_current": 100
}

### ROLL DICE
POST http://localhost:3000/api/rolls 
Content-Type: application/json

{
  "charId": "CH001",
  "result": 15,
  "modifier":-40
}




